### ISSUE TITLE
Open attachmment in browser

### ISSUE THREAD

**Issue by dekkerj1** [ubports/webbrowser-app#10]
At work we have Exchange mail server. I use web mail (owa) via the browser on my Nexu 4 an BQ M10 (OTA-2).
When I want to open or download an attachment from an email I get an error.
This only happens if there are spaces in the filename, for example “Word doc with spaces.doc”
If I choose the option “Download” or “Open with application” after clicking on the attachment, the error is NetworkError: 301 – Protocol “” is unknown. The original name of the attachment is changed in attachment.ashx. There is no problem with downloading or opening the same file on Linux Mint / Firefox.

**Comment by UniversalSuperBox** [comment]
webbrowser-app has been replaced with [morph-browser](https://github.com/ubports/morph-browser). Please file any new issue reports there.
