### ISSUE TITLE
Cannot watch videos

### ISSUE THREAD

**Issue by gitfrank72** [ubports/webbrowser-app#11]
Playing media not possible. When clicking a video following message appears:
"The media could not be loaded,either because the server or network failed or because the format is not supported"

This started in the Canonical-era already, but it seems that nobody is picking up this issue.
brgds, Frank
I am using a Meizu MX4

**Comment by UniversalSuperBox** [comment]
webbrowser-app has been replaced with [morph-browser](https://github.com/ubports/morph-browser). Please file any new issue reports there.
