### ISSUE TITLE
Add Mozilla Storage/Sync support

### ISSUE THREAD

**Issue by dark-eye** [ubports/webbrowser-app#13]
It will be nice to be able to sync with firefox (if possible) this will also allow us to sync with owncloud servers as they support mozilla sync.

**Comment by bhdouglass** [comment]
I was just going to suggest this myself, glad I didn't make a duplicate! It seems this might contain some documentation for the apis: https://mozilla-services.readthedocs.io/en/latest/sync/index.html

**Comment by padraic7a** [comment]
I have posted a more-or-less duplicate issue to browser-ng (https://github.com/ubports/browser-ng/issues/24), I should have taken a look here first.

One quick point - I don't think Owncloud still interacts with Firefox sync - afaik that was in version 1, and things have changed. Long discussion here: https://central.owncloud.org/t/what-happened-to-firefox-sync/10045
