### ISSUE TITLE
"Browser not supported"

### ISSUE THREAD

**Issue by mihaelmilea** [ubports/webbrowser-app#15]
When I access wizzair.com it says "BROWSER IS NOT SUPPORTED". Is there a chance this can be fixed?

Thank you soooo much for all the work!

**Comment by matv1** [comment]
same now for google+ mobile.
:(

**Comment by mihaelmilea** [comment]
Could this be the same bug?: https://github.com/ubports/ubuntu-touch/issues/341

**Comment by NeoTheThird** [comment]
@mihaelmilea Yep, it's the same root problem. In fact it's not related to the browser version at all, but to the user agent string (information about the browser that's sent to the contacted server). From that information, the server can decide if it wants to work or not.

In Ubuntu Touch the user agent string is not fixed, chages depending on what website is supposed to be accessed, what size of a screen is available, what device it's running on, if it's windowed or staged, if it's connected to a display, etc. Additionally, some exceptions for websites who are known to cause problems are hardcoded in oxide.

This is a super annoying design and eventually we'll look into replacing the oxide stack (canonicals fork of chromium that's used in ubuntu touch) with QtWebEngine, but we have to take one step at a time, so for now we'll probably just have to add another exception. Yes, we know, we won't get out of this hole just by digging, but for now oxide still works well enough and we don't want to take any energy out of project sudoku and 15.04 OTA-3 who we think are of greater importance for our users.

**Comment by NeoTheThird** [comment]
Here's an example commit for fixing the user agent for facebook: https://github.com/ubports/webbrowser-app/commit/44b3b9790ddc42864c55164c993d5fb17777033c In case someone is interested in helping with this issue, this would be a good starting point :) Thanks everyone

**Comment by Stefano0101** [comment]
Could we get the exception for Skype for web, Google Plus, Facebook... to be built in? 
Thanks.

**Comment by Julientroploin** [comment]
I read on https://github.com/ubports/ubuntu-touch/issues/341#issuecomment-345016134
that "Oxide is getting a big update in the 16.04 update, cant comment else."

Does it mean it won't be fixed for bq E4.5 ? Or will there be a backport ?

**Comment by UniversalSuperBox** [comment]
morph-browser has succeeded webbrowser-app
