### ISSUE TITLE
Full window video mode - wrong behaviour

### ISSUE THREAD

**Issue by mattbel10** [ubports/webbrowser-app#19]
I noticed that when I'm watching a video in full window mode, always after about 10 minutes the browser by itself decides to exit the full window video mode and refresh the page. I already found out this behaviour with Canonical version.

**Comment by UniversalSuperBox** [comment]
webbrowser-app has been replaced with [morph-browser](https://github.com/ubports/morph-browser). Please file any new issue reports there.
