### ISSUE TITLE
OSK dismiss makes web page flashing

### ISSUE THREAD

**Issue by lduboeuf** [ubports/webbrowser-app#20]
device: krillin OTA 3
related launchpad bug: https://bugs.launchpad.net/oxide/+bug/1660311

web page is flashing when On Screen Keyboard is dismissed.

Step to reproduce:
Access a webpage with form inputs, focus on an input, unfocus input or dismiss OSK, we can see the web page content quickly turn white and then is re rendered.

**Comment by UniversalSuperBox** [comment]
webbrowser-app has been replaced with [morph-browser](https://github.com/ubports/morph-browser). Please file any new issue reports there.
