### ISSUE TITLE
webapp-container does not support recording from microphone

### ISSUE THREAD

**Issue by luksus42** [ubports/webbrowser-app#24]
I am trying to write a html5-app, which needs to record some audio in a blob, to work with.
There is no error, the blob-size is just "0" after recording.

But it's working when I call the same app from the webbrowser-app.
(To test this, I started a python http.server in the www-directory of the app and called http://localhost:8000 in the browser).

The test app can be found here: https://github.com/luksus42/recordingTest
There is also a click build in the build-directory.

I am testing on a bq e4.5.
So I hope someone has an idea how to solve that issue.

**Comment by UniversalSuperBox** [comment]
webbrowser-app has been replaced with [morph-browser](https://github.com/ubports/morph-browser). Please file any new issue reports there.
