### ISSUE TITLE
No easy way to copy URL

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/webbrowser-app#25]
There should be some easy way of copying the current URL to the clipboard. I had expected it in the hamburger menu on the top right (which features "share", but not "copy URL").

Moreover, trying to manually copy the URL from the address box turns out to be tricky. You need to know the right combination of long- and short-clicking the address box to do the magic.

Could you add "copy URL" to the hamburger menu?

**Comment by UniversalSuperBox** [comment]
webbrowser-app has been replaced with [morph-browser](https://github.com/ubports/morph-browser). Please file any new issue reports there.
