### ISSUE TITLE
[xenial] Telegram web-app crashing the browser

### ISSUE THREAD

**Issue by zubozrout** [ubports/webbrowser-app#26]
Hello,
if I go to web.telegram.com the browser pane crashes soon after the site is rendered with the following message:
"The rendering process has been closed for thus tab."
"Something went wrong while displaying https://web.telegram.org/#login."

This applies both on a login screen as well as in the logged in state.

I am running Meizu MX4 with Ubuntu 16.04 (r84) and I've been probably experiencing this ever-since I first switched to 16.04 in early January though I have a faint memory of this working back then. In any case I am sure it doesn't work for several months now.

Please note the same bug affects all Telegram webapps unfortunately.

**Comment by UniversalSuperBox** [comment]
webbrowser-app has been replaced with [morph-browser](https://github.com/ubports/morph-browser). Please file any new issue reports there.
