### ISSUE TITLE
Oxide-qt crashing when external display is connected

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/webbrowser-app#3]
_From @dcostan on June 22, 2017 9:4_

Hey all
On my Aquarius M10 Full Hd with ubports image (frieza) the webbrowser app and other applications using oxide are crashing when I open them with an external display. The same issue happened with the canonical image with lastest OTA.
Thanks all

_Copied from original issue: ubports/webbrowser-component#5_

**Comment by dcostan** [comment]
Similar bug also reported on launchpad during the Canonical era: https://bugs.launchpad.net/ubuntu/+source/webbrowser-app/+bug/1637459
I'm not sure it's the same bug, because with Mir I can't view terminal output of webbrowser-app.

**Comment by UniversalSuperBox** [comment]
webbrowser-app has been replaced with [morph-browser](https://github.com/ubports/morph-browser). Please file any new issue reports there.
