### ISSUE TITLE
Internet Banking site not working (ING Direct, Australia)

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/webbrowser-app#4]
_From @Scott-Marley on June 20, 2017 12:31_

Hi

Not sure if this is an issue with the browser or the site, but when I try to log into my internet banking, I'm denied access because I need to "upgrade" my browser

main site: https://www.ingdirect.com.au/

![screenshot20170619_094427701](https://user-images.githubusercontent.com/29573528/27333089-03a78a1a-5608-11e7-8bff-5de427fbce41.png)

_Copied from original issue: ubports/webbrowser-component#4_

**Comment by NeoTheThird** [comment]
_From @Flohack74 on June 20, 2017 12:38_

Ah yes this is the usual User Agent string problem. They do not accept our UA string to be a compatible browser. See also here: https://github.com/ubports/ubports-touch/issues/17 - which was about a similar problem with being redirected to the desktop version of the site.

I can only say that this will take some time. The integrated browser is no longer supported anyway, and we must switch it out for another thingie. What I really do not understand though is why they do not accept "Chromium/55" or Apple Webkit or Safari in recent version. Do they really have hardcoded Chrome? You might be able to talk to your bank about this. In general its bad practice to hardcode browser names like this.

**Comment by UniversalSuperBox** [comment]
webbrowser-app has been replaced with [morph-browser](https://github.com/ubports/morph-browser). Please file any new issue reports there.
