### ISSUE TITLE
Download fails on already authenticated site

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/webbrowser-app#5]
_From @ernesst on June 11, 2017 1:59_

Reopening the bug here : 

https://bugs.launchpad.net/ubuntu/+source/webbrowser-app/+bug/1581892
https://bugs.launchpad.net/ubuntu/+source/webbrowser-app/+bug/1548020

Some discussion https://lists.launchpad.net/ubuntu-phone/msg22840.html

_Copied from original issue: ubports/webbrowser-component#3_

**Comment by ruedigerkupper** [comment]
Any progress here?

**Comment by rocky58** [comment]
I think no!!!

**Comment by ernesst** [comment]
Yes some, download work from nextcloud/owncloud with : https://open.uappexplorer.com/app/nextcloud.mateosalta

**Comment by mateosalta** [comment]
still work in progress, but should work after a first download(some are experiencing), upload and download with this webapp should be working :)

**Comment by ruedigerkupper** [comment]
Great! Thanks for your work!

**Comment by UniversalSuperBox** [comment]
webbrowser-app has been replaced with [morph-browser](https://github.com/ubports/morph-browser). Please file any new issue reports there.
