### ISSUE TITLE
Problem to access owncloud selfsigned (E4.5)

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/webbrowser-app#6]
_From @j2g2rp on June 8, 2017 12:0_

Hi.
I'm having a problem to access to my ownclod (selfsigned encrypt).
First the webbrowser notices me that it could be risky to access to the page (that isn't a problem really but i don't know if it could be related)
Once that i overrides it, I'm redirected to login page. But there i can't login in to my cloud, looks like the buttons enter of keyboard or arroy from page to login doesn't work at all.
If I'm correct I hadn't this problem in OTA15 from canonical. Now I'm on r8.

_Copied from original issue: ubports/webbrowser-component#2_

**Comment by NeoTheThird** [comment]
_From @ernesst on June 11, 2017 1:56_

A way to solve out is to use Let's encrypt to sign your server. 

It might me because the certificate is selfsigned and not installed in your phone.

**Comment by lapawa** [comment]
The webbrowser-app does not accept custom signed certificates at all.
I'm signing my home services with my own ca and can't find a way to install my own root certificate in the webbrowser-app.

I've inserted the certificate into /usr/local/share/ca-certificates/ and run update-ca-certificates on the phablet, but this did not help. The browser app must have his own certificate store.
Can anyone point me to the right direction.

**Comment by UniversalSuperBox** [comment]
webbrowser-app has been replaced with [morph-browser](https://github.com/ubports/morph-browser). Please file any new issue reports there.
